version: '3'
services:
  cache:
    container_name: cache_doorway_directory_api
    image: redis:6
    networks:
      - network_doorway_directory_api
  
  mysql:
    image: mysql
    restart: always
    container_name: mysql_doorway_directory_api
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./docker/data/database:/var/lib/mysql
      - ./docker/data/initdb.d:/docker-entrypoint-initdb.d
    networks:
      - network_doorway_directory_api
    ports:
      - 3308:3306
    environment:
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_ROOT_PASSWORD: root
  
  nginx:
    container_name: nginx_doorway_directory_api
    depends_on:
      - directus
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: docker/nginx
    ports:
      - "9000:80"
    networks:
      - network_doorway_directory_api
  
  directus:
    container_name: directus_doorway_directory_api
    image: directus/directus:latest
    restart: 'unless-stopped'
    volumes:
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
    networks:
      - network_doorway_directory_api
    depends_on:
      - cache
    environment:
      KEY: ${KEY}"
      SECRET: ${SECRET}"

      DB_CLIENT: "${DB_CLIENT}"
      DB_HOST: "${DB_HOST}"
      DB_PORT: "${DB_PORT}"
      DB_DATABASE: "${DB_DATABASE}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"

      CACHE_ENABLED: "${CACHE_ENABLED}"
      CACHE_STORE: ${CACHE_STORE}"
      CACHE_REDIS: ${CACHE_REDIS}"

      ADMIN_EMAIL: "${ADMIN_EMAIL}"
      ADMIN_PASSWORD: "${ADMIN_PASSWORD}"
networks:
  network_doorway_directory_api: